####################################################################
# Configuration data for DESI survey planning and scheduling.
####################################################################

#-------------------------------------------------------------------
# Location of the Mayall at KPNO
#-------------------------------------------------------------------

location:
    latitude: 31.963972222 deg
    longitude: -111.599336111 deg
    elevation: 2120 m
    pressure: 78318 Pa    # from 1976 standard atmosphere model
    temperature: 5 C      # a guess at mean night-time temperature
    timezone: US/Arizona

#-------------------------------------------------------------------
# Observing calendar.
#-------------------------------------------------------------------

# Survey nominally starts on night of this date. Format is YYYY-MM-DD.
first_day: 2019-12-01

# Survey nominally ends on morning of this date. Format is YYYY-MM-DD.
last_day: 2020-11-30

# First night of monsoon shutdown is on this date each year.
# Format is YYYY-MM-DD but the year is ignored.
monsoon_start: 2019-07-13

# Observing resumes on night of this date each year after monsoon shutdown.
# Format is YYYY-MM-DD but the year is ignored.
monsoon_stop: 2019-08-27

# Number of nights reserved for engineering / guest observing
# during each full moon.
full_moon_nights: 7

#-------------------------------------------------------------------
# Weather forecast.
#-------------------------------------------------------------------

# Percentage probability that the dome is closed during dark time
# due to weather. TODO: find doc-db reference for these (#1658,730,735,993?)
dome_closed_probability:
    jan: 35.24
    feb: 44.14
    mar: 27.68
    apr: 26.73
    may: 14.22
    jun: 15.78
    jul: 55.92
    aug: 48.75
    sep: 29.45
    oct: 24.44
    nov: 24.86
    dec: 34.74

#-------------------------------------------------------------------
# Definition of the DARK / GRAY / BRIGHT nominal programs based on
# sun and moon ephemerides.
#-------------------------------------------------------------------

programs:
    DARK:
        # Twilight requirement.
        max_sun_altitude: -15 deg
        # Moon must be below the horizon.
    GRAY:
        # Twilight requirement is the same as DARK.
        # Moon must be above the horizon and pass both of these cuts:
        max_moon_illumination: 0.6
        max_moon_illumination_altitude_product: 30 deg
    BRIGHT:
        # Twilight requirement.
        max_sun_altitude: -13 deg
        # Any time after twilight that is neither DARK nor GRAY is BRIGHT.

#-------------------------------------------------------------------
# Parameters used to plan observation during a night.
#-------------------------------------------------------------------

# Never observe below this limit.
min_altitude: 30 deg

# Exposure overhead parameters
focus_time: 30 s
slew_overhead: 11.5 s
slew_rate: 0.45 deg / s
readout_time: 2 min

# Exposure time policy parameters
cosmic_ray_split: 20 min
max_exposure_length: 60 min

# The target SNR**2 for each program is specified as the total exposure time
# required at nominal observing conditions.
nominal_exposure_time:
    DARK: 1000 s
    GRAY: 1000 s
    BRIGHT: 300 s
nominal_conditions:
    # Moon below the horizon
    seeing: 1.1 arcsec
    airmass: 1.0
    transparency: 1.0
    EBV: 0.0

# Reobserve tiles that have not reached this fraction of their target SNR**2.
min_snr2_fraction: 0.8

# List of bodies to avoid when scheduling tiles.
avoid_bodies:
    moon: 50 deg
    venus: 2 deg
    mars: 2 deg
    jupiter: 2 deg
    saturn: 2 deg
    neptune: 2 deg
    uranus: 2 deg
    #ceres: 2 deg  # not implemented in pyephem: do we need it?

# Weights for scheduling a tile out of the nominal program, relative
# to 1 for observing a tile from the nominal program.
fallback_weights:
    # DARK program fallback weights.
    gray_in_dark: 0.4
    bright_in_dark: 0.3
    # GRAY program fallback weights.
    dark_in_gray: 0.0
    bright_in_gray: 0.5
    # BRIGHT program fallback weights.
    dark_in_bright: 0.0
    gray_in_bright: 0.0

# Nominal tile radius for determining whether two tiles overlap.
# https://github.com/desihub/desimodel/pull/37#issuecomment-270788581
tile_radius: 1.62 deg

fiber_assignment_order:
    P1: P0
    P2: P0+P1
    P3: P0+P1
    P6: P5
    P7: P5+P6

# Name of file defining DESI tiles for desimodel.io.load_tiles(tiles_file).
# Without path this will look in $DESIMODEL/data/footprint/; otherwise with
# a path (relative or absolute) it will read that file.
tiles_file: desi-tiles.fits

#-------------------------------------------------------------------
# Base path to pre-pended to all non-absolute paths used for writing
# output files. The pattern {...} will be expanded using environment
# variables.
#-------------------------------------------------------------------

output_path: '{DESISURVEY_OUTPUT}'
